#!/bin/sh 

DOCKERFROM=horovod/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.6.0.post0-py3.7-cuda10.1

docker build \
  --rm \
  --no-cache \
  --build-arg dockerfrom=$DOCKERFROM \
  --file Dockerfile \
  --tag pkgpl/pkgpl_base:latest \
  ./
